source "https://rubygems.org"

gem "activerecord"
gem "google-api-client"
gem "httparty"
gem "json"
gem "rest-client"
gem "rqrcode_png"
gem "sanitize"
gem "settingslogic"
gem "sinatra"
gem "sinatra-contrib"
gem "sqlite3"
gem "unicorn"
