base_url: https://<SERVICE_URL>
group_id: <GROUP_ID>
admin_users:
  - <ADMIN_ID>
db:
  name: basketball
  adapter: sqlite3
reservation:
  id: <RESERVATION_SYSTEM_ID>
  password: <RESERVATION_SYSTEM_PASSWORD>
line:
  access_token: <LINE_ACCESS_TOKEN>
google:
  calendar:
    access_code: <GOOGLE_CALENDAR_ACCESS_CODE>
docomo:
  dialogue:
    api_key: <DOCOMO_DIALOGUE_API_KEY>
    context: <DIALOGUE_CONTEXT>
url:
  dropbox: <DROPBOX_MOVIE_URL>
  grafana: <GRAFANA_URL>
  sportsone: http://www.sportsone.jp/xml/events_stock.xml
  crystarea: https://cry55.com/products/list.php?mode=search&area_id[]=12&area_id[]=36&class_id[]=
error:
  db_inconsistency: DBがfollow状況と不整合です。
  user_not_found: ユーザが見つかりませんでした。
notice:
  update: 3
  cancel_day: 5
  cancel_member: 3
color:
  sunday: '#ff4081'
  saturday: '#33CC66'
